### ISSUE TITLE
new feature: add roles to the repository policy

### ISSUE THREAD

**Issue by Schparky** [terraform-aws-modules/terraform-aws-ecr#17]
## Is your request related to a problem? Please describe.
We are currently using our own module to create ECR repositories. It might be good to use and contribute to a more versatile and popular module. A feature that is missing from this fine module is the ability to add roles to the repository policy.

## Describe the solution you'd like.
Add a new variable `repository_role_arns` that accepts one or more IAM role ARNs. If this feature is compatible with this project's design objectives, I could work on a pull request to add this.

## Describe alternatives you've considered.
The alternative is to continue using our own module. An alternative implementation would be to add a `repository_policy` variable that accepts a full policy instead of building in inside the module.

## Additional context
This is the policy we use today:

```hcl
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "ECS Pull Access",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "${ecsInstanceRole_arn}",
                    "${ecsServiceRole_arn}"
                ]
            },
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ]
        },
        {
            "Sid": "CD push/pull",
            "Effect": "Allow",
            "Principal": {
                "AWS": "${cd_user_arn}"
            },
            "Action": [
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ]
        }
    ]
}
```

For reference, the above file is [here](https://github.com/silinternational/terraform-modules/blob/main/aws/ecr/ecr-policy.json)

**Comment by bryantbiggs** [comment]
does the `repository_read_access_arns` not work for your use case?

**Comment by Schparky** [comment]
> does the `repository_read_access_arns` not work for your use case?

Ah, yes, I suppose it would. Somehow I was imagining that roles and users were specified differently in a policy.
