### ISSUE TITLE
Error: creating ECR Public repository: RequestError: send request failed

### ISSUE THREAD

**Issue by hrnn** [terraform-aws-modules/terraform-aws-ecr#18]
## Description

Creating resources against `us-east-2` fails with the following log.

```
│ Error: creating ECR Public repository: RequestError: send request failed
│ caused by: Post "https://api.ecr-public.us-east-2.amazonaws.com/": dial tcp: lookup api.ecr-public.us-east-2.amazonaws.com on 10.2.0.2:53: no such host
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

 1.6.0

- Terraform version:
v1.2.9
- Provider version(s):
registry.terraform.io/hashicorp/aws v5.17.0

## Reproduction Code [Required]

```hcl
provider "aws" {
  region = "us-east-2"
}

module "public_ecr" {
  source = "terraform-aws-modules/ecr/aws"

  repository_name = "public-image"
  repository_type = "public"

  public_repository_catalog_data = {
    description       = "public docker image"
    operating_systems = ["Linux"]
    architectures     = ["x86"]
  }
}

```

**Comment by johnbarney** [comment]
Ran into this too. Public ECR is only in us-east-1 and us-west-2.

https://docs.aws.amazon.com/general/latest/gr/ecr-public.html
