### ISSUE TITLE
the latest module version on the terraform registry is 1.6.0

### ISSUE THREAD

**Issue by jmymy** [terraform-aws-modules/terraform-aws-ecr#31]
## Description

When publishing a module release here, it is not making its way over to the terraform registry
https://registry.terraform.io/modules/terraform-aws-modules/ecr/aws/

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by bryantbiggs** [comment]
oy, this dang registry - cc @antonbabenko

**Comment by antonbabenko** [comment]
Yeah, something is unstable happening with that registry. I will kick it now.

**Comment by antonbabenko** [comment]
Fixed
