### ISSUE TITLE
ECR PullThroughCache implemented credentials_arn when the example documents credential_arn

### ISSUE THREAD

**Issue by fdr2** [terraform-aws-modules/terraform-aws-ecr#35]
In the [complete example](https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/c587836c05941779277671a79d5cd139fc70feb2/examples/complete/main.tf#L145) regarding container pull through cache, either the example reference to credential_arn is incorrect or the [module reference to credentials_arn](https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/c587836c05941779277671a79d5cd139fc70feb2/main.tf#L273) is incorrect.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.1.1 :tada:
