### ISSUE TITLE
Public ECR Resource is missing TAG attribute

### ISSUE THREAD

**Issue by MikeySoftNL** [terraform-aws-modules/terraform-aws-ecr#39]
## Description

When creating a public repository it is not supplied the var.tags variable value

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version 2.2.0

## Reproduction Code [Required]

module "ecr_public" {
  source = "terraform-aws-modules/ecr/aws"

  repository_name                 = "my-ecr"
  repository_type = "public"

  tags = { Name = "my-ecr" }
}

## Expected behavior

Terraform Plan SHOULD show

resource "aws_ecrpublic_repository" "this" {
  ....
  tags = { Name = "my-ecr" }
  ....
}

## Actual behavior

resource "aws_ecrpublic_repository" "this" {
  ....
  tags            = {}
  ....
}

## Solution

in **main.tf** on line 240 add

tags = var.tags

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.2.1 :tada:
