### ISSUE TITLE
Non-unique SID in policy

### ISSUE THREAD

**Issue by dheitman-prom** [terraform-aws-modules/terraform-aws-ecr#50]
## Description

When using `repository_read_write_access_arns`, a duplicate SID is created in the IAM policy document.  Multiple dynamic statements keyed to `repository_read_write_access_arns` use the same `ReadWrite` SID.

https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/124c13976f4cdc061f5b1ddb38bff715eeba2ad5/modules/repository-template/main.tf#L104
https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/124c13976f4cdc061f5b1ddb38bff715eeba2ad5/modules/repository-template/main.tf#L124

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 2.3.0, master

- Terraform version: Any, doesn't matter

## Reproduction Code [Required]

Set any value for the `repository_read_write_access_arns` variable

## Expected behavior

Work mo betta.  Basically have different SID values for the two lines linked at the top of this report

## Actual behavior

`Error: writing IAM Policy Document: duplicate Sid (ReadWrite). Remove the Sid or ensure the Sid is unique`

**Comment by bryantbiggs** [comment]
we are unable to help troubleshoot without a reproduction

we do set these values in the examples and they work without issue
- https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/124c13976f4cdc061f5b1ddb38bff715eeba2ad5/examples/complete/main.tf#L35
- https://github.com/terraform-aws-modules/terraform-aws-ecr/blob/124c13976f4cdc061f5b1ddb38bff715eeba2ad5/examples/complete/main.tf#L66

**Comment by dheitman-prom** [comment]
This is specifically for the `repository-template` submodule, see links above.  Your examples for the submodule don't use that variable, so they don't encounter the bug.  It's very obvious, it's two statements with the same sid, one of the two lines I linked needs to be changed to a different sid.  I'll submit a patch tomorrow.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.3.1 :tada:
